"""Build install.sh / uninstall.sh for jt-ocr-server remote deployment.

The GENERATED scripts are pure ASCII (no CJK) — they run on GPU hosts that
may have no Chinese locale. This Python source file (builder.py itself) may
use CJK for our own documentation.

Safety design (don't break the remote env):
  - Never touch system Python (always use isolated venv)
  - Never install GPU driver / kernel modules (only verify nvidia-smi)
  - Never modify system PATH / shell rc / firewall
  - Atomic install (stage in /tmp, mv to /opt at the end)
  - Refuse to overwrite existing install_dir without --force
  - Bundle uninstall.sh in install_dir for clean removal
  - Service runs as dedicated system user (jt-ocr), not root

DGX Spark specifics (aarch64 + GB10 Blackwell sm_120):
  - Install PyTorch from https://download.pytorch.org/whl/cu128
  - Requires ~3GB disk + outbound network
  - DGX Spark ships without bare-metal PyTorch (user verified)
"""
from __future__ import annotations

from pathlib import Path


def _read_server_template() -> str:
    """Load server_template.py content; embedded as heredoc in install.sh."""
    p = Path(__file__).parent / "server_template.py"
    return p.read_text(encoding="utf-8")


def build_install_script(
    *,
    install_dir: str = "/opt/jt-ocr-server",
    service_port: int = 8766,
    service_user: str = "jt-ocr",
    jtdt_version: str = "",
) -> str:
    """Produce a self-contained install.sh. All output strings ASCII-only."""
    server_py = _read_server_template()
    if "SERVER_PY_EOF" in server_py:
        raise ValueError("server_template.py contains forbidden marker SERVER_PY_EOF")

    script_version = jtdt_version or "dev"
    return f"""#!/bin/bash
# ============================================================================
# jt-ocr-server install script
# Generated by jt-doc-tools{f" v{jtdt_version}" if jtdt_version else ""}
# ============================================================================
SCRIPT_VERSION="{script_version}"
#
# Usage:
#   scp install.sh root@GPU-HOST:/tmp/
#   ssh root@GPU-HOST 'bash /tmp/install.sh [--dry-run] [--force]'
#
# Safety:
#   - Never touches system Python (uses dedicated venv only)
#   - Never installs GPU driver / kernel modules (verifies nvidia-smi only)
#   - Never modifies system PATH / shell rc / firewall
#   - Atomic install (stage -> atomic mv)
#   - Refuses to overwrite existing dir/port without --force
#   - Bundles uninstall.sh in install dir
# ============================================================================
set -euo pipefail

INSTALL_DIR="${{INSTALL_DIR:-{install_dir}}}"
SERVICE_PORT="${{SERVICE_PORT:-{service_port}}}"
SERVICE_USER="${{SERVICE_USER:-{service_user}}}"
DRY_RUN=0
FORCE=0
LOG_FILE="/var/log/jt-ocr-server-install.log"

show_help() {{
    cat <<EOF
jt-ocr-server install script

Usage: bash install.sh [OPTIONS]

Options:
  --dry-run            Detect only; do not modify anything
  --force              Overwrite existing install directory
  --port N             Override service port (default: {service_port})
  --install-dir PATH   Override install directory (default: {install_dir})
  --service-user U     Override service user (default: {service_user})
  --help               Show this help

Environment overrides:
  INSTALL_DIR, SERVICE_PORT, SERVICE_USER

Safety:
  * Isolated venv (does not touch system Python)
  * Does NOT install GPU driver (verifies nvidia-smi only)
  * Does NOT modify system PATH / firewall
  * Atomic install (staging dir -> mv)
  * Bundles uninstall.sh in install dir
EOF
}}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry-run)      DRY_RUN=1; shift ;;
        --force)        FORCE=1; shift ;;
        --port)         SERVICE_PORT="$2"; shift 2 ;;
        --install-dir)  INSTALL_DIR="$2"; shift 2 ;;
        --service-user) SERVICE_USER="$2"; shift 2 ;;
        --help|-h)      show_help; exit 0 ;;
        *) echo "Unknown option: $1" >&2; show_help; exit 2 ;;
    esac
done

log()    {{ echo "[$(date +%H:%M:%S)] $*" | tee -a "$LOG_FILE"; }}
fail()   {{ log "[FAIL] $*"; exit 1; }}
banner() {{ echo; log "=== $* ==="; }}

if ! touch "$LOG_FILE" 2>/dev/null; then
    LOG_FILE="/tmp/jt-ocr-server-install.log"
    touch "$LOG_FILE" 2>/dev/null || LOG_FILE=/dev/null
fi
log "Log file:     $LOG_FILE"
log "Install dir:  $INSTALL_DIR"
log "Service port: $SERVICE_PORT"
log "Service user: $SERVICE_USER"
log "Mode:         $([[ $DRY_RUN = 1 ]] && echo 'DRY-RUN' || echo 'INSTALL')"

# ============================================================================
# Phase 1: Pre-flight checks (read-only)
# ============================================================================
banner "Phase 1: Pre-flight checks"

# 1.1 root
if [[ "$(id -u)" != "0" ]]; then
    fail "must run as root (use: sudo bash install.sh)"
fi
log "[OK] running as root"

# 1.2 architecture
ARCH=$(uname -m)
log "[OK] architecture: $ARCH"
case "$ARCH" in
    x86_64|aarch64) ;;
    *) fail "unsupported architecture: $ARCH (only x86_64 and aarch64 are supported)" ;;
esac

# 1.3 OS detect
if [[ -f /etc/os-release ]]; then
    . /etc/os-release
    OS_NAME="${{NAME:-unknown}}"
    OS_VER="${{VERSION_ID:-unknown}}"
    log "[OK] os: $OS_NAME $OS_VER"
fi

# 1.4 DGX detect
IS_DGX=0
if [[ -f /etc/dgx-release ]]; then
    IS_DGX=1
    log "[OK] DGX Spark / DGX OS detected (/etc/dgx-release present)"
fi

# 1.5 nvidia-smi
if ! command -v nvidia-smi >/dev/null 2>&1; then
    fail "nvidia-smi not found. Install NVIDIA driver first. This script does NOT install drivers."
fi
if ! nvidia-smi >/dev/null 2>&1; then
    fail "nvidia-smi exists but fails to run. Check driver installation / kernel module."
fi
GPU_NAME=$(nvidia-smi --query-gpu=name --format=csv,noheader | head -1)
GPU_DRIVER=$(nvidia-smi --query-gpu=driver_version --format=csv,noheader | head -1)
log "[OK] GPU: $GPU_NAME (driver $GPU_DRIVER)"

# 1.6 python -- accept PYTHON= env override (e.g. PYTHON=/usr/bin/python3.12)
PYTHON="${{PYTHON:-python3}}"
if ! command -v "$PYTHON" >/dev/null 2>&1; then
    fail "python interpreter not found: $PYTHON (override with PYTHON=/path/to/python3.X)"
fi
PY_VER=$("$PYTHON" -c 'import sys; print(f"{{sys.version_info.major}}.{{sys.version_info.minor}}")')
PY_MAJ=$("$PYTHON" -c 'import sys; print(sys.version_info.major)')
PY_MIN=$("$PYTHON" -c 'import sys; print(sys.version_info.minor)')
if [[ "$PY_MAJ" != "3" ]] || [[ "$PY_MIN" -lt 10 ]]; then
    fail "Python $PY_VER too old (need 3.10+; override with PYTHON=/usr/bin/python3.12)"
fi
log "[OK] python: $PY_VER ($($PYTHON -c 'import sys; print(sys.executable)'))"

# 1.7 venv module -- must test by actually creating a venv (Ubuntu splits
# `ensurepip` data into a Python-version-specific package; `import venv`
# can succeed while `python -m venv` fails for missing ensurepip).
if ! "$PYTHON" -c "import venv" 2>/dev/null; then
    fail "python3-venv missing. Install with: apt install python3-venv python${{PY_VER}}-venv"
fi
_venv_probe=$(mktemp -d /tmp/jt-ocr-venv-probe.XXXXXX)
if ! "$PYTHON" -m venv "$_venv_probe/.venv" >/dev/null 2>&1; then
    rm -rf "$_venv_probe"
    fail "python -m venv FAILS even though 'import venv' works. Install: apt install python${{PY_VER}}-venv (Python ${{PY_VER}} specific ensurepip data)"
fi
rm -rf "$_venv_probe"
log "[OK] python3-venv working ($("$PYTHON" -c 'import venv; print(venv.__file__)' | head -1))"

# 1.7b Warn on Python > 3.13 (PyTorch wheels often lag for newest Python)
if [[ "$PY_MIN" -gt 13 ]]; then
    log "[!!] Python $PY_VER is newer than PyTorch's typical wheel support (3.9-3.13)."
    log "     If install fails at PyTorch step, install Python 3.12 alongside and rerun:"
    log "       apt install python3.12-venv && PYTHON=/usr/bin/python3.12 bash install.sh"
fi

# 1.8 detect pre-installed torch (reuse if found, saves ~3GB)
PRE_TORCH=""
PRE_TORCH_VER=""
if "$PYTHON" -c 'import torch' 2>/dev/null; then
    PRE_TORCH="$("$PYTHON" -c 'import sys; print(sys.executable)')"
    PRE_TORCH_VER=$("$PYTHON" -c 'import torch; print(torch.__version__)')
    PRE_TORCH_CUDA=$("$PYTHON" -c 'import torch; print(torch.cuda.is_available())')
    log "[OK] system PyTorch detected: $PRE_TORCH_VER (cuda=$PRE_TORCH_CUDA) - will reuse"
else
    log "[..] system PyTorch not found - will install (~3GB)"
fi

# 1.9 existing install_dir - skip if same version and service healthy
if [[ -d "$INSTALL_DIR" ]]; then
    # detect existing install version (written to .install_version on success)
    EXISTING_VER=""
    if [[ -f "$INSTALL_DIR/.install_version" ]]; then
        EXISTING_VER=$(cat "$INSTALL_DIR/.install_version" 2>/dev/null | tr -d '[:space:]')
    fi
    if [[ "$FORCE" != "1" ]] && [[ -n "$EXISTING_VER" ]] && [[ "$EXISTING_VER" = "$SCRIPT_VERSION" ]]; then
        # Same version - check if service is running, if so, all good
        if systemctl is-active --quiet jt-ocr-server 2>/dev/null; then
            log "[OK] Already installed at version $SCRIPT_VERSION and service is active. Nothing to do."
            log "     Use --force to reinstall anyway."
            HOST_IP=$(hostname -I 2>/dev/null | awk '{{print $1}}')
            [[ -z "$HOST_IP" ]] && HOST_IP="<this-host-ip>"
            SERVICE_PORT_DETECT=$(grep -oP 'JT_OCR_PORT=\\K\\d+' /etc/systemd/system/jt-ocr-server.service 2>/dev/null || echo "$SERVICE_PORT")
            TOKEN_EXISTING=$(cat "$INSTALL_DIR/token" 2>/dev/null || echo "<unable to read>")
            echo
            echo "============================================================"
            echo "[SKIP] jt-ocr-server v$SCRIPT_VERSION already installed and running"
            echo "============================================================"
            echo
            echo "  URL:    http://$HOST_IP:$SERVICE_PORT_DETECT"
            echo "  Token:  $TOKEN_EXISTING"
            echo
            echo "  To force reinstall: bash $0 --force"
            echo "  To uninstall:       bash $INSTALL_DIR/uninstall.sh"
            echo
            exit 0
        else
            log "[..] same version ($SCRIPT_VERSION) but service not running - will reinstall"
        fi
    fi
    if [[ "$FORCE" != "1" ]] && [[ -n "$EXISTING_VER" ]] && [[ "$EXISTING_VER" != "$SCRIPT_VERSION" ]]; then
        log "[..] existing install version: $EXISTING_VER, new script version: $SCRIPT_VERSION - upgrading"
        FORCE=1  # auto-force for version upgrade
    fi
    if [[ "$FORCE" != "1" ]]; then
        fail "$INSTALL_DIR already exists (version unknown). Use --force to overwrite, or run $INSTALL_DIR/uninstall.sh first."
    fi
    log "[!!] force-overwriting existing $INSTALL_DIR"
fi

# 1.10 existing service
if systemctl list-unit-files 2>/dev/null | grep -q '^jt-ocr-server\\.service'; then
    if [[ "$FORCE" != "1" ]]; then
        fail "jt-ocr-server.service already exists. Use --force to overwrite."
    fi
    log "[!!] force-overwriting existing jt-ocr-server.service"
fi

# 1.11 port check
if ss -tln 2>/dev/null | grep -q ":$SERVICE_PORT "; then
    fail "Port $SERVICE_PORT is in use. Use --port N to change."
fi
log "[OK] port $SERVICE_PORT available"

# 1.12 disk space
FREE_MB=$(df -m "$(dirname "$INSTALL_DIR")" 2>/dev/null | awk 'NR==2{{print $4}}' || echo 0)
if [[ -z "$PRE_TORCH" ]] && [[ "$FREE_MB" -lt 4000 ]]; then
    fail "Insufficient disk: ${{FREE_MB}}MB free, need >4GB (includes PyTorch ~3GB)"
fi
if [[ -n "$PRE_TORCH" ]] && [[ "$FREE_MB" -lt 1000 ]]; then
    fail "Insufficient disk: ${{FREE_MB}}MB free, need >1GB"
fi
log "[OK] disk free: ${{FREE_MB}} MB"

# 1.13 network to PyPI
if ! curl -fsSL -m 5 https://pypi.org/simple/ -o /dev/null 2>&1; then
    fail "cannot reach https://pypi.org - check outbound network / proxy"
fi
log "[OK] network to PyPI"

# Decide install strategy
TORCH_INSTALL_MODE=""
TORCH_INDEX=""
if [[ -n "$PRE_TORCH" ]]; then
    TORCH_INSTALL_MODE="reuse-system"
elif [[ "$ARCH" = "aarch64" ]]; then
    TORCH_INSTALL_MODE="install"
    TORCH_INDEX="https://download.pytorch.org/whl/cu128"
    log "[..] aarch64 -> using PyTorch cu128 wheels (Blackwell sm_120 / DGX Spark)"
else
    # cu128 has broader Python version support (incl. 3.13+) + newer GPU coverage
    # (Blackwell RTX PRO 6000 etc.). cu124 wheels lag and miss Python 3.14.
    TORCH_INSTALL_MODE="install"
    TORCH_INDEX="https://download.pytorch.org/whl/cu128"
    log "[..] x86_64 -> using PyTorch cu128 wheels (newer Python + Blackwell coverage)"
fi

if [[ "$DRY_RUN" = "1" ]]; then
    banner "Dry-run complete"
    log "Would perform on actual run:"
    log "  - create system user '$SERVICE_USER' (if missing)"
    log "  - create venv at $INSTALL_DIR/.venv"
    log "  - install PyTorch: $TORCH_INSTALL_MODE${{TORCH_INDEX:+ from $TORCH_INDEX}}"
    log "  - install easyocr / fastapi / uvicorn"
    log "  - write server.py + uninstall.sh"
    log "  - register systemd unit + start service"
    log "  - NO changes to system Python / driver / PATH / firewall"
    echo
    echo "============================================================"
    echo "[SUCCESS] DRY-RUN PASSED - all pre-flight checks OK"
    echo "============================================================"
    echo
    echo "No files were written. To proceed with actual install:"
    echo
    echo "  # If running directly on the GPU host:"
    echo "  bash $0"
    echo
    echo "  # If running remotely from another machine:"
    echo "  ssh root@<GPU-HOST> 'bash $0'"
    echo
    exit 0
fi

# ============================================================================
# Phase 2: Install (writes start here)
# ============================================================================
banner "Phase 2: Install"

STAGE=$(mktemp -d /tmp/jt-ocr-stage.XXXXXX)
log "[..] staging dir: $STAGE"

cleanup_stage() {{
    if [[ -d "$STAGE" ]]; then
        log "[!!] failure detected, cleaning up staging $STAGE"
        rm -rf "$STAGE"
    fi
}}
trap cleanup_stage EXIT ERR

# 2.1 venv
log "[..] creating Python venv..."
if [[ "$TORCH_INSTALL_MODE" = "reuse-system" ]]; then
    "$PYTHON" -m venv --system-site-packages "$STAGE/.venv"
    log "     venv inherits system-site-packages (reusing pre-installed torch=$PRE_TORCH_VER)"
else
    "$PYTHON" -m venv "$STAGE/.venv"
fi
"$STAGE/.venv/bin/pip" install -q -U pip

# 2.2 PyTorch
if [[ "$TORCH_INSTALL_MODE" = "install" ]]; then
    log "[..] installing PyTorch (2-3GB, 5-15 min depending on network)..."
    if ! "$STAGE/.venv/bin/pip" install -q torch torchvision --index-url "$TORCH_INDEX"; then
        log "[FAIL] PyTorch install failed (index=$TORCH_INDEX, Python=$PY_VER)"
        if [[ "$PY_MIN" -gt 13 ]]; then
            log "       PyTorch likely doesn't ship wheels for Python $PY_VER yet."
            log "       Workaround: install Python 3.12 + rerun:"
            log "         apt install python3.12 python3.12-venv"
            log "         PYTHON=/usr/bin/python3.12 bash $0"
        else
            log "       Try the default PyPI index (CPU wheels, no GPU acceleration):"
            log "         $STAGE/.venv/bin/pip install torch torchvision"
        fi
        fail "PyTorch install failed"
    fi
    log "[OK] PyTorch installed"
fi

# 2.3 EasyOCR + FastAPI
log "[..] installing easyocr / fastapi / uvicorn..."
"$STAGE/.venv/bin/pip" install -q easyocr fastapi 'uvicorn[standard]' python-multipart pillow \\
    || fail "easyocr / fastapi install failed"
log "[OK] EasyOCR + FastAPI installed"

# 2.4 smoke test PyTorch CUDA
log "[..] smoke test PyTorch CUDA..."
"$STAGE/.venv/bin/python" -c "
import torch
print('torch:', torch.__version__)
print('cuda_available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('device:', torch.cuda.get_device_name(0))
else:
    raise SystemExit('torch.cuda.is_available() returned False - driver/CUDA mismatch?')
" || fail "PyTorch CUDA smoke test failed - driver / cuda may be incompatible with PyTorch"

# 2.5 write server.py
log "[..] writing server.py..."
cat > "$STAGE/server.py" << 'SERVER_PY_EOF'
{server_py}
SERVER_PY_EOF
"$STAGE/.venv/bin/python" -c "import ast; ast.parse(open('$STAGE/server.py').read())" \\
    || fail "server.py syntax error"
log "[OK] server.py written"

# 2.6 generate token
TOKEN=$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | xxd -p -c 32)
echo "$TOKEN" > "$STAGE/token"
chmod 600 "$STAGE/token"
log "[OK] token generated"

# 2.7 service user
if ! id "$SERVICE_USER" >/dev/null 2>&1; then
    useradd -r -s /bin/false -d "$INSTALL_DIR" "$SERVICE_USER"
    log "[OK] created system user '$SERVICE_USER'"
else
    log "[OK] system user '$SERVICE_USER' already exists"
fi

# 2.8 bundle uninstall.sh
cat > "$STAGE/uninstall.sh" << 'UNINSTALL_EOF'
#!/bin/bash
# jt-ocr-server uninstall - does NOT touch system Python / driver / firewall
set -e
INSTALL_DIR="$(cd "$(dirname "$0")" && pwd)"
echo "Uninstalling jt-ocr-server from $INSTALL_DIR"
echo "(stops/removes service + removes $INSTALL_DIR;"
echo " does NOT touch system Python / driver / firewall)"
read -p "Continue? [y/N]: " confirm
[[ "$confirm" =~ ^[Yy]$ ]] || {{ echo "Aborted"; exit 0; }}

systemctl stop jt-ocr-server 2>/dev/null || true
systemctl disable jt-ocr-server 2>/dev/null || true
rm -f /etc/systemd/system/jt-ocr-server.service
systemctl daemon-reload

read -p "Also remove EasyOCR model cache (~/.EasyOCR/, ~150MB)? [y/N]: " del_cache
if [[ "$del_cache" =~ ^[Yy]$ ]]; then
    rm -rf /root/.EasyOCR ~/.EasyOCR 2>/dev/null || true
    if id "SERVICE_USER_PLACEHOLDER" >/dev/null 2>&1; then
        rm -rf "$(eval echo ~SERVICE_USER_PLACEHOLDER)/.EasyOCR" 2>/dev/null || true
    fi
fi

read -p "Also remove service user 'SERVICE_USER_PLACEHOLDER'? [y/N]: " del_user
if [[ "$del_user" =~ ^[Yy]$ ]]; then
    userdel SERVICE_USER_PLACEHOLDER 2>/dev/null || true
fi

rm -rf "$INSTALL_DIR"
echo "[OK] uninstall complete"
UNINSTALL_EOF
sed -i "s/SERVICE_USER_PLACEHOLDER/$SERVICE_USER/g" "$STAGE/uninstall.sh"
chmod +x "$STAGE/uninstall.sh"

# 2.9 README (use quoted heredoc so $vars and backticks stay literal)
cat > "$STAGE/README.md" << 'README_EOF'
# jt-ocr-server

EasyOCR GPU service for jt-doc-tools remote OCR.

## Status

    systemctl status jt-ocr-server
    journalctl -u jt-ocr-server -f

## Endpoints

- GET  /healthz   - unauthenticated liveness + GPU info
- POST /ocr       - multipart image + langs, requires Bearer token
- GET  /version   - requires Bearer token

## Token

    cat /opt/jt-ocr-server/token

## Restart / Stop

    systemctl restart jt-ocr-server
    systemctl stop jt-ocr-server

## Uninstall

    bash /opt/jt-ocr-server/uninstall.sh

Generated by jt-doc-tools install.sh
README_EOF

# 2.10 atomic mv into install_dir
if [[ -d "$INSTALL_DIR" ]] && [[ "$FORCE" = "1" ]]; then
    log "[..] removing existing $INSTALL_DIR..."
    systemctl stop jt-ocr-server 2>/dev/null || true
    rm -rf "$INSTALL_DIR"
fi
mkdir -p "$(dirname "$INSTALL_DIR")"
mv "$STAGE" "$INSTALL_DIR"
trap - EXIT ERR
chown -R "$SERVICE_USER:$SERVICE_USER" "$INSTALL_DIR"
log "[OK] installed to $INSTALL_DIR"

# 2.11 systemd unit
log "[..] registering systemd unit..."
cat > /etc/systemd/system/jt-ocr-server.service << EOF
[Unit]
Description=jt-ocr-server (EasyOCR GPU service for jt-doc-tools)
After=network.target

[Service]
Type=simple
User=$SERVICE_USER
Group=$SERVICE_USER
WorkingDirectory=$INSTALL_DIR
Environment=JT_OCR_TOKEN_FILE=$INSTALL_DIR/token
Environment=JT_OCR_PORT=$SERVICE_PORT
# Min free VRAM (MB) a GPU needs to be auto-selected on multi-GPU hosts.
# The server picks the eligible GPU with the most free VRAM, else falls back
# to CPU. Lower this if your cards are small; 0 disables the threshold.
Environment=JT_OCR_MIN_FREE_MB=2048
ExecStart=$INSTALL_DIR/.venv/bin/python $INSTALL_DIR/server.py
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable jt-ocr-server >/dev/null 2>&1
systemctl start jt-ocr-server
log "[OK] systemd unit registered and started"

# 2.12 smoke test service
log "[..] smoke testing service (waiting 5s for startup)..."
sleep 5
HEALTH=""
for i in 1 2 3 4 5; do
    if HEALTH=$(curl -fsS -m 5 "http://127.0.0.1:$SERVICE_PORT/healthz" 2>/dev/null); then
        break
    fi
    sleep 2
done

if [[ -z "$HEALTH" ]]; then
    log "[FAIL] service smoke test failed"
    log "       systemctl status jt-ocr-server"
    log "       journalctl -u jt-ocr-server -n 50"
    exit 1
fi

log "[OK] service healthy:"
log "     $HEALTH"

# 2.13 write version marker for idempotent re-install detection
echo "$SCRIPT_VERSION" > "$INSTALL_DIR/.install_version"
chown "$SERVICE_USER:$SERVICE_USER" "$INSTALL_DIR/.install_version"

HOST_IP=$(hostname -I 2>/dev/null | awk '{{print $1}}')
[[ -z "$HOST_IP" ]] && HOST_IP="<this-host-ip>"

# ============================================================================
# Done
# ============================================================================
echo
echo "############################################################"
echo "##                                                        ##"
echo "##  [SUCCESS] jt-ocr-server INSTALL COMPLETE              ##"
echo "##                                                        ##"
echo "############################################################"
echo
echo "  URL:    http://$HOST_IP:$SERVICE_PORT"
echo "  Token:  $TOKEN"
echo
echo "------------------------------------------------------------"
echo "  Next step:"
echo "    Open jtdt admin -> OCR Lang -> EasyOCR section"
echo "    Paste URL + Token above"
echo "    Click 'Test connection' then 'Save' to enable."
echo "------------------------------------------------------------"
echo
echo "  Service commands:"
echo "    status:    systemctl status jt-ocr-server"
echo "    log:       journalctl -u jt-ocr-server -f"
echo "    restart:   systemctl restart jt-ocr-server"
echo "    uninstall: bash $INSTALL_DIR/uninstall.sh"
echo
echo "############################################################"
"""


def build_uninstall_script(install_dir: str = "/opt/jt-ocr-server") -> str:
    """Standalone uninstall.sh. ASCII-only."""
    return f"""#!/bin/bash
# jt-ocr-server standalone uninstall script
# Removes service + install dir; does NOT touch system Python / driver / firewall
set -e
INSTALL_DIR="${{1:-{install_dir}}}"

if [[ "$(id -u)" != "0" ]]; then
    echo "must run as root" >&2
    exit 1
fi

echo "About to uninstall jt-ocr-server:"
echo "  Install dir: $INSTALL_DIR"
echo "(stops/removes service + removes install dir;"
echo " does NOT touch system Python / driver / firewall)"
read -p "Continue? [y/N]: " confirm
[[ "$confirm" =~ ^[Yy]$ ]] || {{ echo "Aborted"; exit 0; }}

systemctl stop jt-ocr-server 2>/dev/null || true
systemctl disable jt-ocr-server 2>/dev/null || true
rm -f /etc/systemd/system/jt-ocr-server.service
systemctl daemon-reload

rm -rf "$INSTALL_DIR"
echo "[OK] uninstall complete"
echo
echo "To also remove EasyOCR model cache (~/.EasyOCR/):"
echo "  rm -rf ~/.EasyOCR /root/.EasyOCR /home/jt-ocr/.EasyOCR"
echo
echo "To also remove service user 'jt-ocr':"
echo "  userdel jt-ocr"
"""
