"""jt-ocr-server - EasyOCR FastAPI service for GPU acceleration.

This file is EMBEDDED as a heredoc into the install.sh script generated by
build_install_script(). It does NOT execute as part of jt-doc-tools - it runs
on the remote GPU host inside the deployed venv.

ASCII-only (no CJK strings) - GPU host may lack Chinese locale.

API:
  POST /ocr          multipart: image (PNG/JPG bytes)
                     form:      langs (e.g. "ch_tra+en"), preprocess (bool)
                     header:    Authorization: Bearer <token>
                     -> {engine, version, device, elapsed_s,
                         words: [{text, bbox: [x0,y0,x1,y1], conf}]}
  GET  /healthz      -> {ok, gpu, vram_free_mb, vram_total_mb, easyocr, torch}
  GET  /version     -> {server, easyocr, torch, cuda_available, device_name}

Auth: every endpoint except /healthz requires Bearer token matching the
JT_OCR_TOKEN_FILE contents. /healthz is unauthenticated so basic monitoring
works without exposing the token.

Design notes:
  - Lazy-load Reader per langs combo, keep in memory dict (langs_key -> reader)
  - Single threaded uvicorn (worker=1) - EasyOCR GPU calls already serialize on GPU
  - Logs to stdout (systemd captures into journal)
"""
from __future__ import annotations

import io
import logging
import os
import time
from typing import Any

from fastapi import FastAPI, File, Form, HTTPException, Header, UploadFile
from fastapi.responses import JSONResponse

SERVER_VERSION = "1.0.0"

logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
log = logging.getLogger("jt-ocr-server")

# Token loaded once at startup
TOKEN_FILE = os.environ.get("JT_OCR_TOKEN_FILE", "/opt/jt-ocr-server/token")
try:
    with open(TOKEN_FILE, encoding="utf-8") as _fh:
        SERVICE_TOKEN = _fh.read().strip()
    if not SERVICE_TOKEN:
        raise RuntimeError("token file empty")
except Exception as _e:
    log.error("Failed to read token from %s: %s", TOKEN_FILE, _e)
    SERVICE_TOKEN = ""

app = FastAPI(title="jt-ocr-server", version=SERVER_VERSION)

# Reader cache: "ch_tra+en" -> easyocr.Reader instance
_readers: dict[str, Any] = {}


def _require_auth(authorization: str | None) -> None:
    if not SERVICE_TOKEN:
        raise HTTPException(500, "server token not configured")
    if not authorization or not authorization.startswith("Bearer "):
        raise HTTPException(401, "missing Bearer token")
    presented = authorization.removeprefix("Bearer ").strip()
    # constant-time compare
    import hmac
    if not hmac.compare_digest(presented, SERVICE_TOKEN):
        raise HTTPException(401, "invalid token")


def _normalize_langs(langs: str) -> list[str]:
    """Accept "ch_tra+en" or "ch_tra,en" or "ch_tra en" -> ["ch_tra", "en"]."""
    raw = langs.replace(",", "+").replace(" ", "+")
    out = [l.strip() for l in raw.split("+") if l.strip()]
    # Whitelist: only lowercase ascii letters and underscores (matches EasyOCR codes).
    # Anything containing CR/LF or other characters is rejected (prevents log injection).
    import re as _re
    out = [c for c in out if _re.fullmatch(r"[a-z_]{2,10}", c)]
    return out or ["en"]


def _safe_log_str(s) -> str:
    """Strip CR/LF and limit length for safe logging (prevents log injection)."""
    text = str(s)[:200]
    return text.replace("\r", "?").replace("\n", "?")


def _get_reader(langs_list: list[str]):
    """Lazy-load EasyOCR Reader for a langs combination, cache for reuse."""
    import easyocr  # type: ignore
    import torch  # type: ignore

    key = "+".join(sorted(langs_list))
    if key in _readers:
        return _readers[key]

    gpu_ok = torch.cuda.is_available()
    safe_langs = _safe_log_str(langs_list)
    safe_key = _safe_log_str(key)
    log.info("Loading EasyOCR Reader for langs=%s (gpu=%s)", safe_langs, gpu_ok)
    t0 = time.time()
    reader = easyocr.Reader(langs_list, gpu=gpu_ok, verbose=False)
    log.info("Reader for %s loaded in %.1fs", safe_key, time.time() - t0)
    _readers[key] = reader
    return reader


def _to_int_list(bbox) -> list[int]:
    """EasyOCR returns bbox as [[x0,y0],[x1,y0],[x1,y1],[x0,y1]] (polygon).
    Reduce to axis-aligned [x0, y0, x1, y1]."""
    xs = [int(p[0]) for p in bbox]
    ys = [int(p[1]) for p in bbox]
    return [min(xs), min(ys), max(xs), max(ys)]


@app.get("/healthz")
def healthz() -> JSONResponse:
    """Unauthenticated liveness check."""
    info: dict[str, Any] = {"ok": True, "server": SERVER_VERSION}
    try:
        import torch  # type: ignore
        info["torch"] = torch.__version__
        info["cuda_available"] = torch.cuda.is_available()
        if torch.cuda.is_available():
            info["gpu"] = torch.cuda.get_device_name(0)
            # mem_get_info may fail if other processes (Ollama etc.) saturated VRAM -
            # don't treat as a hard error, just skip VRAM stats.
            try:
                free, total = torch.cuda.mem_get_info(0)
                info["vram_free_mb"] = round(free / 1024 / 1024)
                info["vram_total_mb"] = round(total / 1024 / 1024)
            except Exception as _e:
                info["vram_note"] = f"unavailable: {_e.__class__.__name__}"
    except Exception as e:
        info["torch_error"] = str(e).splitlines()[0][:200]
    try:
        import easyocr  # type: ignore
        info["easyocr"] = easyocr.__version__ if hasattr(easyocr, "__version__") else "?"
    except Exception as e:
        info["easyocr_error"] = str(e)
    info["readers_cached"] = list(_readers.keys())
    return JSONResponse(info)


@app.get("/version")
def version(authorization: str | None = Header(default=None)) -> JSONResponse:
    _require_auth(authorization)
    info: dict[str, Any] = {"server": SERVER_VERSION}
    try:
        import torch  # type: ignore
        info["torch"] = torch.__version__
        info["cuda_available"] = torch.cuda.is_available()
        if torch.cuda.is_available():
            info["device_name"] = torch.cuda.get_device_name(0)
    except Exception:
        pass
    try:
        import easyocr  # type: ignore
        info["easyocr"] = easyocr.__version__ if hasattr(easyocr, "__version__") else "?"
    except Exception:
        pass
    return JSONResponse(info)


@app.post("/ocr")
async def ocr(
    image: UploadFile = File(...),
    langs: str = Form("en"),
    preprocess: bool = Form(False),
    authorization: str | None = Header(default=None),
) -> JSONResponse:
    _require_auth(authorization)
    raw = await image.read()
    if not raw:
        raise HTTPException(400, "empty image")
    if len(raw) > 50 * 1024 * 1024:
        raise HTTPException(400, "image > 50MB")

    langs_list = _normalize_langs(langs)
    try:
        reader = _get_reader(langs_list)
    except Exception as e:
        log.exception("Reader load failed for langs=%s", _safe_log_str(langs_list))
        raise HTTPException(500, "reader load failed") from e

    # Decode image with PIL -> numpy for EasyOCR
    try:
        from PIL import Image  # type: ignore
        import numpy as np  # type: ignore
        img = Image.open(io.BytesIO(raw))
        if img.mode != "RGB":
            img = img.convert("RGB")
        if preprocess:
            from PIL import ImageFilter  # type: ignore
            img = img.filter(ImageFilter.MedianFilter(size=3))
        arr = np.array(img)
    except Exception as e:
        raise HTTPException(400, f"image decode failed: {e}") from e

    t0 = time.time()
    try:
        results = reader.readtext(arr, detail=1, paragraph=False)
    except Exception as e:
        log.exception("readtext failed")
        raise HTTPException(500, f"readtext failed: {e}") from e
    elapsed = time.time() - t0

    words = []
    for r in results:
        bbox, text, conf = r[0], r[1], r[2]
        bbox_int = _to_int_list(bbox)
        words.append({
            "text": str(text),
            "bbox": bbox_int,
            "conf": float(conf),
        })

    import torch  # type: ignore
    return JSONResponse({
        "engine": "easyocr",
        "device": "cuda" if torch.cuda.is_available() else "cpu",
        "elapsed_s": round(elapsed, 3),
        "n_words": len(words),
        "words": words,
    })


if __name__ == "__main__":
    import uvicorn  # type: ignore
    port = int(os.environ.get("JT_OCR_PORT", "8766"))
    host = os.environ.get("JT_OCR_HOST", "0.0.0.0")
    log.info("starting jt-ocr-server v%s on %s:%d", SERVER_VERSION, host, port)
    log.info("token file: %s (loaded: %s)", TOKEN_FILE, "yes" if SERVICE_TOKEN else "NO")
    uvicorn.run(app, host=host, port=port, log_level="info")
